version: "3"

services:
  front:
    image: front:tag_name_front
    build: ./inovation-labs-FE
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - ecs-react-node
  back:
    image: back:tag_name_back
    build: ./inovation-labs-BE
    ports:
      - "3001:3001"
    networks:
      - ecs-react-node
networks:
  ecs-react-node:
    driver: bridge
